### ISSUE TITLE
Compile error on OSX with rand 0.6

### ISSUE THREAD

**Issue by jcjones** [jcjones/u2f-hid-rs#76]
Works fine with rand v0.5.5
```
   Compiling rand v0.6.4
error[E0425]: cannot find function `pthread_atfork` in module `libc`
   --> /Users/jcjones/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.6.4/src/rngs/adapter/reseeding.rs:320:28
    |
320 |             unsafe { libc::pthread_atfork(None, None, Some(fork_handler)) };
    |                            ^^^^^^^^^^^^^^ not found in `libc`
```

**Comment by dhardy** [comment]
On which platform? @jonathanKingston implies this on OSX but libc appears to define `pthread_atfork` on "macos".

**Comment by jcjones** [comment]
Fixed in https://github.com/jcjones/u2f-hid-rs/commit/7fac8b1f384f35c84b2ee35daf2defef763375c4
